# Generated by Django 2.2.14 on 2020-07-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='node',
            field=models.ManyToManyField(related_name='Categories', to='home.Node'),
        ),
    ]
