# Generated by Django 3.0.8 on 2020-07-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('blog', '0002_blogpage_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='node',
            field=models.ManyToManyField(to='home.Node'),
        ),
    ]
