# Generated by Django 3.0.8 on 2020-07-13 16:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('blog', '0003_auto_20200713_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='node',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Node'),
        ),
    ]
