# Generated by Django 3.0.8 on 2020-07-23 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200718_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpagerelatedproduct',
            name='related_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='blog.BlogPage'),
        ),
    ]
