# Generated by Django 3.0.8 on 2020-07-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200723_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='node',
        ),
    ]
