# Generated by Django 3.0.8 on 2020-07-26 03:39

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_node'),
        ('blog', '0009_remove_blogpage_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='node',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Node'),
        ),
    ]
