# Generated by Django 3.0.8 on 2020-07-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_advblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advblock',
            name='description',
        ),
    ]
