# Generated by Django 3.0.8 on 2020-07-31 21:35

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200731_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewitem',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_items', to='blog.ReviewPage'),
        ),
    ]
