# Generated by Django 3.0.8 on 2020-08-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200731_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpage',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
    ]
