# Generated by Django 3.0.8 on 2020-08-03 17:48

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200730_2013'),
        ('blog', '0019_reviewfeature_reviewspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpage',
            name='node',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='home.Node'),
        ),
    ]
