# Generated by Django 3.0.8 on 2020-07-15 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200713_2116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
