# Generated by Django 3.0.8 on 2020-07-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogpage_node'),
        ('home', '0006_homepage_search_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
    ]
