# Generated by Django 3.0.8 on 2020-07-26 02:08

import django.core.validators
from django.db import migrations, models
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text='Keep the name short, ideally one word.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message="Letters, numbers and '&' only plus must start with a letter.", regex='^[\\w][a-zA-Z &]+$'), django.core.validators.MinLengthValidator(3)])),
                ('aliases', models.TextField(blank=True, help_text='What else is this known as or referred to as?', max_length=255, verbose_name='Also known as')),
                ('node_order_index', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
