# Generated by Django 3.0.8 on 2020-07-17 16:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200717_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='themecolorscheme',
            name='body_bg_color_primary',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='body_bg_color_seconday',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='brand_text_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='bsp_bg_color',
            field=colorfield.fields.ColorField(default='#4693aa', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='bsp_text_color',
            field=colorfield.fields.ColorField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='footer_bg_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='footer_text_color',
            field=colorfield.fields.ColorField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='megamenu_bg_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='megamenu_footer_bg_color',
            field=colorfield.fields.ColorField(default='#4693aa', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='megamenu_footer_text_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='megamenu_text_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='megamenu_text_hover_color',
            field=colorfield.fields.ColorField(default='#4693aa', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='subnav_bg_color',
            field=colorfield.fields.ColorField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='subnav_text_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='theme_color',
            field=colorfield.fields.ColorField(default='#4693aa', max_length=10),
        ),
    ]
