# Generated by Django 3.0.8 on 2020-07-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('menu', '0002_auto_20200714_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitemfooteritem',
            name='footer_item_image',
        ),
        migrations.AddField(
            model_name='menuitemfooteritem',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
