# Generated by Django 3.0.8 on 2020-07-17 16:29

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200717_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='font',
            name='title',
            field=models.CharField(default='Lato', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
    ]
