# Generated by Django 3.0.8 on 2020-07-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200717_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themecolorscheme',
            old_name='body_bg_color_seconday',
            new_name='body_bg_color_secondary',
        ),
    ]
