# Generated by Django 3.0.8 on 2020-07-18 18:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_contactitem_footerdetails_subscriptionemail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerdetails',
            options={'verbose_name_plural': 'Footer Details'},
        ),
        migrations.AddField(
            model_name='footerdetails',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title'),
        ),
        migrations.AddField(
            model_name='footerdetails',
            name='title',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
