# Generated by Django 3.0.8 on 2020-07-18 23:12

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_footercolumn_footercolumnrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercolumnrow',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_rows', to='menu.FooterColumn'),
        ),
    ]
