# Generated by Django 3.0.8 on 2020-07-23 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('menu', '0009_auto_20200718_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemfooteritem',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image'),
        ),
    ]
