# Generated by Django 3.0.8 on 2020-07-29 22:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20200723_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='themecolorscheme',
            name='advertise_block_text_color',
            field=colorfield.fields.ColorField(default='white', max_length=10),
        ),
        migrations.AddField(
            model_name='themecolorscheme',
            name='categories_bg_color',
            field=colorfield.fields.ColorField(default='black', max_length=10),
        ),
    ]
